### ISSUE TITLE
[SUGGEST]

### ISSUE THREAD

**Issue by Diotek0** [MinusMC/MinusBounce#3]
Mong các dev thêm midclick, rotation range (hoặc tên khác là "aim range"), killaura perfect hit (hit select), lagrange (blink range)

**Comment by fmcpe** [comment]
MidClick: .friend add *** (nếu tay có bị làm sao thì t sẽ add trong vài ngày tiếp)
RotationRange: wait for fixes (bị ngu nếu += movementcorrection) (sẽ cố gắng fix)
Perfect Hit:???? I don't know and i don't care
Lag range: done

**Comment by Diotek0** [comment]
top 1 dev của minus

**Comment by fmcpe** [comment]
xac nhan se khong lam rotation range vi li do : bi conflict voi move correction and who need it btw?
